import { addDays } from "date-fns"
import { PositionType, EngineeringType, Application } from "@prisma/client"
import type { CardProps } from "@/components/ui/interfaces"

const today = new Date()

export const mockCards: CardProps[] = [
    {
        bgImage:
            "https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2340&q=80",
        mainTitle: "Follow the Warwick Engineering Society",
        subtitle: "Stay updated with our latest events and opportunities",
        link: "https://warwick.ac.uk/fac/sci/eng/",
        textColour: "text-white",
        linkText: "Follow Us",
    },
    {
        bgImage:
            "https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2340&q=80",
        mainTitle: "Upcoming Events",
        subtitle: "Join us for our next networking event on 25th November 2024!",
        link: "https://warwick.ac.uk/fac/sci/eng/events/",
        textColour: "text-white",
        linkText: "View Events",
    },
    {
        bgImage:
            "https://images.unsplash.com/photo-1523240795612-9a054b0db644?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2340&q=80",
        mainTitle: "Engineering Careers Fair",
        subtitle: "Meet top employers and explore career opportunities",
        link: "https://warwick.ac.uk/fac/sci/eng/careers/",
        textColour: "text-white",
        linkText: "Learn More",
    },
]

export const mockApplications: Omit<Application, "id">[] = [
    {
        programme: "Graduate Engineer",
        company: "Rolls-Royce",
        type: PositionType.Graduate,
        engineering: [EngineeringType.Mechanical],
        openDate: addDays(today, 2),
        closeDate: addDays(today, 15),
        requiresCv: true,
        requiresCoverLetter: true,
        requiresWrittenAnswers: true,
        notes: "Online assessment required",
        link: "https://careers.rolls-royce.com/",
        isSponsored: true,
        verified: false,
    },
    {
        programme: "Summer Internship",
        company: "Arup",
        type: PositionType.Internship,
        engineering: [EngineeringType.Civil],
        openDate: addDays(today, 1),
        closeDate: addDays(today, 5),
        requiresCv: true,
        requiresCoverLetter: false,
        requiresWrittenAnswers: true,
        notes: "Portfolio recommended",
        link: "https://www.arup.com/careers",
        isSponsored: false,
        verified: false,
    },
    {
        programme: "Industrial Placement",
        company: "Jaguar Land Rover",
        type: PositionType.Placement,
        engineering: [EngineeringType.Mechanical, EngineeringType.Electronic],
        openDate: addDays(today, 3),
        closeDate: addDays(today, 10),
        requiresCv: true,
        requiresCoverLetter: true,
        requiresWrittenAnswers: false,
        notes: "12-month placement",
        link: "https://www.jaguarlandrovercareers.com/",
        isSponsored: true,
        verified: false,
    },
    {
        programme: "Software Engineering Intern",
        company: "IBM",
        type: PositionType.Internship,
        engineering: [EngineeringType.Software, EngineeringType.Computing],
        openDate: addDays(today, 1),
        closeDate: addDays(today, 7),
        requiresCv: true,
        requiresCoverLetter: false,
        requiresWrittenAnswers: true,
        notes: "Coding challenge required",
        link: "https://www.ibm.com/uk-en/employment/",
        isSponsored: false,
        verified: false,
    },
    {
        programme: "Graduate Scheme",
        company: "BAE Systems",
        type: PositionType.Graduate,
        engineering: [EngineeringType.Aerospace, EngineeringType.Electronic],
        openDate: addDays(today, 4),
        closeDate: addDays(today, 28),
        requiresCv: true,
        requiresCoverLetter: true,
        requiresWrittenAnswers: true,
        notes: "Security clearance required",
        link: "https://www.baesystems.com/en/careers",
        isSponsored: true,
        verified: false,
    },
    {
        programme: "Year in Industry",
        company: "Siemens",
        type: PositionType.Placement,
        engineering: [EngineeringType.Electronic, EngineeringType.Software],
        openDate: addDays(today, 3),
        closeDate: addDays(today, 8),
        requiresCv: true,
        requiresCoverLetter: true,
        requiresWrittenAnswers: false,
        notes: "German language skills preferred",
        link: "https://new.siemens.com/uk/en/company/jobs.html",
        isSponsored: true,
        verified: false,
    },
    {
        programme: "Research Internship",
        company: "University of Warwick",
        type: PositionType.Internship,
        engineering: [EngineeringType.Chemical, EngineeringType.Computing],
        openDate: addDays(today, 5),
        closeDate: addDays(today, 14),
        requiresCv: true,
        requiresCoverLetter: true,
        requiresWrittenAnswers: true,
        notes: "Lab experience required",
        link: "https://warwick.ac.uk/fac/sci/eng/",
        isSponsored: false,
        verified: false,
    },
    {
        programme: "Graduate Development Programme",
        company: "National Grid",
        type: PositionType.Graduate,
        engineering: [EngineeringType.Electronic, EngineeringType.Civil],
        openDate: addDays(today, 7),
        closeDate: addDays(today, 18),
        requiresCv: true,
        requiresCoverLetter: true,
        requiresWrittenAnswers: true,
        notes: "Multiple rotations across UK",
        link: "https://careers.nationalgrid.com/",
        isSponsored: true,
        verified: false,
    },
    {
        programme: "Robotics Engineering Intern",
        company: "Boston Dynamics",
        type: PositionType.Internship,
        engineering: [EngineeringType.Mechanical, EngineeringType.Software],
        openDate: addDays(today, 4),
        closeDate: addDays(today, 17),
        requiresCv: true,
        requiresCoverLetter: true,
        requiresWrittenAnswers: true,
        notes: "Experience with ROS preferred",
        link: "https://www.bostondynamics.com/careers",
        isSponsored: false,
        verified: false,
    },
    {
        programme: "Environmental Engineering Graduate",
        company: "Atkins",
        type: PositionType.Graduate,
        engineering: [EngineeringType.Civil, EngineeringType.Chemical],
        openDate: addDays(today, 6),
        closeDate: addDays(today, 23),
        requiresCv: true,
        requiresCoverLetter: true,
        requiresWrittenAnswers: false,
        notes: "Sustainability focus",
        link: "https://careers.snclavalin.com/",
        isSponsored: true,
        verified: false,
    },
]

