import { addDays } from 'date-fns'
import { ApplicationType } from '../schemas/applications'
import { CardProps } from '@/components/ui/interfaces'

const today = new Date('2024-11-17')
export const mockCards: CardProps[] = [ // Updated from mockCards to cards
    {
        bgImage: "https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2340&q=80",
        mainTitle: "Follow the Warwick Engineering Society",
        subtitle: "Stay updated with our latest events and opportunities",
        link: "https://warwick.ac.uk/fac/sci/eng/",
        textColour: "text-white",
        linkText: "Follow Us" // Updated to include linkText
    },
    {
        bgImage: "https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2340&q=80",
        mainTitle: "Upcoming Events",
        subtitle: "Join us for our next networking event on 25th November 2024!",
        link: "https://warwick.ac.uk/fac/sci/eng/events/",
        textColour: "text-white",
        linkText: "View Events" // Updated to include linkText
    },
    {
        bgImage: "https://images.unsplash.com/photo-1523240795612-9a054b0db644?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2340&q=80",
        mainTitle: "Engineering Careers Fair",
        subtitle: "Meet top employers and explore career opportunities",
        link: "https://warwick.ac.uk/fac/sci/eng/careers/",
        textColour: "text-white",
        linkText: "Learn More" // Updated to include linkText
    },
]
export const mockApplications: ApplicationType[] = [
    {
        id: "1",
        programme: "Graduate Engineer",
        company: "Rolls-Royce",
        type: "Graduate",
        engineering: "Mechanical",
        openDate: addDays(today, 5).toISOString(),
        closeDate: addDays(today, 45).toISOString(),
        requiresCv: true,
        requiresCoverLetter: true,
        requiresWrittenAnswers: true,
        notes: "Online assessment required",
        link: "https://careers.rolls-royce.com/",
    },
    {
        id: "2",
        programme: "Summer Internship",
        company: "Arup",
        type: "Internship",
        engineering: "Civil",
        openDate: addDays(today, 2).toISOString(),
        closeDate: addDays(today, 10).toISOString(),
        requiresCv: true,
        requiresCoverLetter: false,
        requiresWrittenAnswers: true,
        notes: "Portfolio recommended",
        link: "https://www.arup.com/careers",
    },
    {
        id: "3",
        programme: "Industrial Placement",
        company: "Jaguar Land Rover",
        type: "Placement",
        engineering: "Automotive",
        openDate: addDays(today, 7).toISOString(),
        closeDate: addDays(today, 30).toISOString(),
        requiresCv: true,
        requiresCoverLetter: true,
        requiresWrittenAnswers: false,
        notes: "12-month placement",
        link: "https://www.jaguarlandrovercareers.com/",
    },
    {
        id: "4",
        programme: "Software Engineering Intern",
        company: "IBM",
        type: "Internship",
        engineering: "Computer",
        openDate: addDays(today, 3).toISOString(),
        closeDate: addDays(today, 15).toISOString(),
        requiresCv: true,
        requiresCoverLetter: false,
        requiresWrittenAnswers: true,
        notes: "Coding challenge required",
        link: "https://www.ibm.com/uk-en/employment/",
    },
    {
        id: "5",
        programme: "Graduate Scheme",
        company: "BAE Systems",
        type: "Graduate",
        engineering: "Aerospace",
        openDate: addDays(today, 10).toISOString(),
        closeDate: addDays(today, 60).toISOString(),
        requiresCv: true,
        requiresCoverLetter: true,
        requiresWrittenAnswers: true,
        notes: "Security clearance required",
        link: "https://www.baesystems.com/en/careers",
    },
    {
        id: "6",
        programme: "Year in Industry",
        company: "Siemens",
        type: "Placement",
        engineering: "Electrical",
        openDate: addDays(today, 8).toISOString(),
        closeDate: addDays(today, 20).toISOString(),
        requiresCv: true,
        requiresCoverLetter: true,
        requiresWrittenAnswers: false,
        notes: "German language skills preferred",
        link: "https://new.siemens.com/uk/en/company/jobs.html",
    },
    {
        id: "7",
        programme: "Research Internship",
        company: "University of Warwick",
        type: "Internship",
        engineering: "Biomedical",
        openDate: addDays(today, 15).toISOString(),
        closeDate: addDays(today, 40).toISOString(),
        requiresCv: true,
        requiresCoverLetter: true,
        requiresWrittenAnswers: true,
        notes: "Lab experience required",
        link: "https://warwick.ac.uk/fac/sci/eng/",
    },
    {
        id: "8",
        programme: "Graduate Development Programme",
        company: "National Grid",
        type: "Graduate",
        engineering: "Electrical",
        openDate: addDays(today, 20).toISOString(),
        closeDate: addDays(today, 55).toISOString(),
        requiresCv: true,
        requiresCoverLetter: true,
        requiresWrittenAnswers: true,
        notes: "Multiple rotations across UK",
        link: "https://careers.nationalgrid.com/",
    },
    {
        id: "9",
        programme: "Robotics Engineering Intern",
        company: "Boston Dynamics",
        type: "Internship",
        engineering: "Mechanical",
        openDate: addDays(today, 12).toISOString(),
        closeDate: addDays(today, 50).toISOString(),
        requiresCv: true,
        requiresCoverLetter: true,
        requiresWrittenAnswers: true,
        notes: "Experience with ROS preferred",
        link: "https://www.bostondynamics.com/careers",
    },
    {
        id: "10",
        programme: "Environmental Engineering Graduate",
        company: "Atkins",
        type: "Graduate",
        engineering: "Environmental",
        openDate: addDays(today, 18).toISOString(),
        closeDate: addDays(today, 70).toISOString(),
        requiresCv: true,
        requiresCoverLetter: true,
        requiresWrittenAnswers: false,
        notes: "Sustainability focus",
        link: "https://careers.snclavalin.com/",
    },
    {
        id: "11",
        programme: "Chemical Process Engineer",
        company: "Shell",
        type: "Graduate",
        engineering: "Chemical",
        openDate: addDays(today, 25).toISOString(),
        closeDate: addDays(today, 80).toISOString(),
        requiresCv: true,
        requiresCoverLetter: true,
        requiresWrittenAnswers: true,
        notes: "HAZOP experience beneficial",
        link: "https://www.shell.com/careers",
    },
    {
        id: "12",
        programme: "Aerospace Systems Intern",
        company: "Airbus",
        type: "Internship",
        engineering: "Aerospace",
        openDate: addDays(today, 30).toISOString(),
        closeDate: addDays(today, 90).toISOString(),
        requiresCv: true,
        requiresCoverLetter: false,
        requiresWrittenAnswers: true,
        notes: "Avionics knowledge preferred",
        link: "https://www.airbus.com/careers",
    },
    {
        id: "13",
        programme: "Nuclear Engineering Placement",
        company: "EDF Energy",
        type: "Placement",
        engineering: "Nuclear",
        openDate: addDays(today, 35).toISOString(),
        closeDate: addDays(today, 100).toISOString(),
        requiresCv: true,
        requiresCoverLetter: true,
        requiresWrittenAnswers: true,
        notes: "18-month placement opportunity",
        link: "https://www.edfenergy.com/careers",
    },
    {
        id: "14",
        programme: "Biomedical Device Innovation",
        company: "Medtronic",
        type: "Graduate",
        engineering: "Biomedical",
        openDate: addDays(today, 40).toISOString(),
        closeDate: addDays(today, 110).toISOString(),
        requiresCv: true,
        requiresCoverLetter: true,
        requiresWrittenAnswers: false,
        notes: "FDA regulation knowledge a plus",
        link: "https://www.medtronic.com/uk-en/about/careers.html",
    },
    {
        id: "15",
        programme: "Automotive Design Intern",
        company: "McLaren Automotive",
        type: "Internship",
        engineering: "Automotive",
        openDate: addDays(today, 45).toISOString(),
        closeDate: addDays(today, 120).toISOString(),
        requiresCv: true,
        requiresCoverLetter: true,
        requiresWrittenAnswers: true,
        notes: "CAD proficiency required",
        link: "https://careers.mclaren.com/",
    },
    {
        id: "16",
        programme: "Structural Engineering Intern",
        company: "Mott MacDonald",
        type: "Internship",
        engineering: "Civil",
        openDate: addDays(today, 50).toISOString(),
        closeDate: addDays(today, 130).toISOString(),
        requiresCv: true,
        requiresCoverLetter: true,
        requiresWrittenAnswers: false,
        notes: "Experience with AutoCAD preferred",
        link: "https://www.mottmac.com/careers",
    },
    {
        id: "17",
        programme: "Renewable Energy Graduate Scheme",
        company: "Ørsted",
        type: "Graduate",
        engineering: "Electrical",
        openDate: addDays(today, 55).toISOString(),
        closeDate: addDays(today, 140).toISOString(),
        requiresCv: true,
        requiresCoverLetter: true,
        requiresWrittenAnswers: true,
        notes: "Focus on offshore wind energy",
        link: "https://orsted.com/en/careers",
    },
    {
        id: "18",
        programme: "Robotics and Automation Placement",
        company: "ABB",
        type: "Placement",
        engineering: "Mechatronics",
        openDate: addDays(today, 60).toISOString(),
        closeDate: addDays(today, 150).toISOString(),
        requiresCv: true,
        requiresCoverLetter: false,
        requiresWrittenAnswers: true,
        notes: "Programming skills required",
        link: "https://global.abb/group/en/careers",
    },
    {
        id: "19",
        programme: "Aerospace Systems Engineer",
        company: "Leonardo",
        type: "Graduate",
        engineering: "Aerospace",
        openDate: addDays(today, 65).toISOString(),
        closeDate: addDays(today, 160).toISOString(),
        requiresCv: true,
        requiresCoverLetter: true,
        requiresWrittenAnswers: true,
        notes: "Security clearance may be required",
        link: "https://www.leonardo.com/en/careers",
    },
    {
        id: "20",
        programme: "Materials Science Internship",
        company: "Johnson Matthey",
        type: "Internship",
        engineering: "Materials",
        openDate: addDays(today, 70).toISOString(),
        closeDate: addDays(today, 170).toISOString(),
        requiresCv: true,
        requiresCoverLetter: false,
        requiresWrittenAnswers: true,
        notes: "Lab-based role",
        link: "https://matthey.com/en/careers",
    },
    {
        id: "21",
        programme: "Water Treatment Engineer",
        company: "Veolia",
        type: "Graduate",
        engineering: "Environmental",
        openDate: addDays(today, 75).toISOString(),
        closeDate: addDays(today, 180).toISOString(),
        requiresCv: true,
        requiresCoverLetter: true,
        requiresWrittenAnswers: false,
        notes: "Multiple UK locations available",
        link: "https://www.veolia.co.uk/careers",
    },
    {
        id: "22",
        programme: "Automotive Design Placement",
        company: "Bentley Motors",
        type: "Placement",
        engineering: "Automotive",
        openDate: addDays(today, 80).toISOString(),
        closeDate: addDays(today, 190).toISOString(),
        requiresCv: true,
        requiresCoverLetter: true,
        requiresWrittenAnswers: true,
        notes: "Portfolio submission required",
        link: "https://www.bentleycareers.com/",
    },
    {
        id: "23",
        programme: "Chemical Process Engineering Intern",
        company: "INEOS",
        type: "Internship",
        engineering: "Chemical",
        openDate: addDays(today, 85).toISOString(),
        closeDate: addDays(today, 200).toISOString(),
        requiresCv: true,
        requiresCoverLetter: false,
        requiresWrittenAnswers: true,
        notes: "Safety certification advantageous",
        link: "https://www.ineos.com/careers/",
    },
    {
        id: "24",
        programme: "Nuclear Decommissioning Graduate",
        company: "Sellafield Ltd",
        type: "Graduate",
        engineering: "Nuclear",
        openDate: addDays(today, 90).toISOString(),
        closeDate: addDays(today, 210).toISOString(),
        requiresCv: true,
        requiresCoverLetter: true,
        requiresWrittenAnswers: true,
        notes: "Requires relocation to Cumbria",
        link: "https://www.sellafieldsite.co.uk/careers/",
    },
    {
        id: "25",
        programme: "Biomedical Engineering Placement",
        company: "Smith & Nephew",
        type: "Placement",
        engineering: "Biomedical",
        openDate: addDays(today, 95).toISOString(),
        closeDate: addDays(today, 220).toISOString(),
        requiresCv: true,
        requiresCoverLetter: true,
        requiresWrittenAnswers: false,
        notes: "Interest in medical devices required",
        link: "https://www.smith-nephew.com/careers/",
    }
]
